version: "3"

tasks:
  start:
    aliases:
      - run
    desc: "Run service through local env variable"
    cmds:
        - CONFIG_PATH="./config/local.yaml" go run ./cmd/sso/main.go

  startfl:
    aliases:
      - runf
    desc: "Run service through flag (priority)"
    cmds:
      - go run ./cmd/sso/main.go --config="./config/local.yaml"

  build:
    desc: "Build program without docstrings and information about debugging (imporve performance)"
    cmds:
      - go build -o ./sso  -ldflags "-s -w" ./cmd/sso/main.go
      - chmod +x ./sso

  startex:
    desc: "Run executable file with local env variable"
    aliases:
      - "runex"
    cmds:
      - CONFIG_PATH="./config/local.yaml" ./sso"

  startexfl:
    desc: "Run executable file with flag (priority)"
    aliases:
      - "runexf"
    cmds:
      - ./sso --config="./config/local.yaml"

  migrations:
    deps: [download-all-dependencies]
    desc: "Run migrations in database"
    aliases:
      - "migrate"
    cmds:
      - mkdir -p storage
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations


  download-all-dependencies:
    internal: true
    desc: "Download and installing all dependencies for migrations"
    cmds:
      - go get github.com/mattn/go-sqlite3
      - go get github.com/golang-migrate/migrate/v4
      - go mod tidy
